[package]
name = "rusty_roguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
chrono = "0.4.26"
legion = "=0.3.1"
mockall = "0.11.4"
ron = "0.8.0"
serde = "1.0.164"
